spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3307/inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia%2FJakarta}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Jakarta

server:
  port: ${SERVER_PORT:8080}

app:
  product-image-directory: ${PRODUCT_IMAGE_DIR:uploads/products}
